name: ak_golden_project
description: "A Bakery E-commerce Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  sizer: ^3.0.4
  font_awesome_flutter: ^10.3.0
  flutter_advanced_segment: ^3.0.2
  intl: ^0.17.0
  carousel_slider: ^5.0.0
  http:
  shared_preferences: ^2.0.15
  keyboard_avoider: ^0.2.0
  google_fonts: ^6.2.1
  jwt_decoder: ^2.0.1
  persistent_bottom_nav_bar: ^6.2.1
  flutter_onboarding_slider: ^1.0.11
  introduction_screen: ^3.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/


